### PR TITLE
Refactor and Modernise snapcraft.yaml

### PR DESCRIPTION
**Pull request by ghost**
Purpose and Advantages Of This Refactoring:
1) Uses the latest core.
2) Uses simpler method of integrating snap with kde-neon sdk and runtime, making it easy to be maintained.
3) Using kde-neon sdk and runtime reduces snap complexity.
4) Makes building latest version of the app easy.

Assurances:
1) Tested locally with snapcraft remote-build on amd64, works fine

Drawbacks:
1) Only available for amd64 currently as kde-neon doesn;t support other architectures. 

The older build method is complex and redundant plus its not a pure build i.e, changes/modifies a lot of upstream code, thus diverging snap package away from  the vanilla builds.
The snap yaml must be made easy to be maintained so that in future any other maintainer can overtake it.

Although this will bring lot of conflicting changes with the older snap as such it will be kept currently in pipeline only.

### CODE REVIEW

**Comment by ghost** [comment]
ToDo:
1) Make user aware of newer changes using --> https://forum.snapcraft.io/t/inform-users-with-custom-dialogs/10825/2

**Comment by brlin-tw** [comment]
> Only available for amd64 currently as kde-neon doesn;t support other architectures.

It appears that [the core22 variant of the kde-neon extension actually supports ARM64](https://snapcraft.io/kf5-5-106-qt-5-15-9-core22):

Screenshot

in that case, we should enable them in [the architecture stanza](https://github.com/brlin-tw/featherpad-snap/pull/12/files#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5R7) as well.

While I don't specifically oppose changes that will obsolete support of the existing architectures, it would not be nice for the users to be not aware of it.  A final update should be built and pushed to display an obsoletion notice of the snap on these architectures, as the snap based on the new recipe will not be installable on these machines this can't be done in this PR and should target the old upstream version that is still buildable (i.e. 0.16.0).

**Comment by ghost** [comment]
@brlin-tw  So whats the way forward, the snap is already way outdated, you can co-author a zenity gui regarding the depreciation i believe ??, i have tested the kde-arm but it actually breaks few times when building and sometimes it build.

**Comment by ghost** [comment]
@brlin-tw  Do Tell me when you will try this version of snap yaml to publish the snap, the snap is outdated, we need to publish the latest version asap if possible or when should i merge it ??

**Pull request closed without merging**
